name: 'ReadMe API GitHub Sync'
description: 'Sync API Spec files to ReadMe automatically'
author: 'ReadMe'
branding:
  icon: 'code'
  color: 'blue'
inputs:
  readme-oas-key:
    description: 'Your ReadMe key, which we give you when setting up GitHub Sync in ReadMe!'

  oas-file-path:
    description: 'The relative path for your API spec file (Default: We try to guess!)'
  api-version:
    description: 'ReadMe version to sync API into (Default: info.version in your schema)'
  oas-file-url:
    description: 'Remote Url for your api spec'
runs:
  using: 'node12'
  main: 'main.js'
